# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6156eb31b42a0637143c75e2a57c161f82352b76d30c0d5c98844b502bbde7834a3eeef8633f72602d7938e27b2f06b034e0a5195fe5be5f324a034b0ca4432

test:
  secret_key_base: e514398452b5f21508a74043b675affe7a160edf482f1d18cb0dc4391d775ca2836610c074932e3017a6e27ec05014375e2887bfc6873e44e65fdc32ac5c009c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
